---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

library(tidyverse)
library(magick)

```

```{css}
body {
  color: white;
  background-color: #733493;
  line-height: 2;
  font-family: 'Raleway', sans-serif;
}
p {
  font-weight: normal;
  font-family: 'Quicksand', sans-serif;
}

```

## Patterns of Phone Use in Public Spaces

This form is designed to capture brief observations of phone usage in public areas. Its aim is to gather information on the nature of phone activities, the situational context, and the length of time the phone is used.

```{r}
csv_file <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vTRTaioXRkrCqyQKO49F7zdTbDvV1BsqhdRlngD3tI0sfc-JLx63qtKP5AgqJ3iKKgJ6LVKt4Z1mIeP/pub?gid=824138341&single=true&output=csv"

header <- image_blank(width = 700, height = 100, color = "#733493") %>%
  image_annotate(
    text = "Observed Phone Use by Location and Activity",
    color = "white",
    size = 25,
    gravity = "west",
    font = "Raleway",
  )

header

logged_data <- read.csv(csv_file)

latest_data <- logged_data %>%
  rename(phone_activity = 2,
         minutes = 3,
         observ_loc = 4,
         time_of_day = 5)
```

```{r, echo=FALSE}
latest_data %>%
  ggplot(aes(x = observ_loc)) +
  geom_bar(fill = "#681768") +
  theme_minimal() +
  labs(title = "Observations by Location",
       x = "Location",
       y = "Observations")

```

```{r, echo=FALSE}
latest_data %>%
  ggplot(aes(x = phone_activity)) +
  geom_bar(fill = "#681768") +
  theme_minimal() +
  labs(title = "Types of Phone Activity Observed",
       x = "Activity Type",
       y = "Observations")
```

```{r, echo=FALSE}
paste("The minimum time spent on the phone was", min(latest_data$minutes), "minutes.")
```

```{r, echo=FALSE}
paste("The maximum time spent on the phone was", max(latest_data$minutes), "minutes.")
```

```{r, echo=FALSE}
summary_img <- image_blank(width = 600, height = 150, color = "#733493") %>%
  image_annotate(
    text = paste0( "Phone Use Summary\n",
      "Min: ", min(latest_data$minutes), " minutes   |   ",
      "Max: ", max(latest_data$minutes), " minutes"),
     color = "white",
     size = 30,
     gravity = "center",
     font = "Quicksand")

summary_img
```
